<?php

declare(strict_types=1);

namespace Castor\Docker\Tests\Unit\Service;

use Castor\Docker\Service\Builder\ComposeBuilder;
use Castor\Docker\Service\MariaDBService;
use Castor\Docker\Service\MySQLService;
use Castor\Docker\Service\ServiceInterface;
use Castor\Docker\Tests\SnapshotTestCase;

/**
 * The MySQL-family servers read every "*.cnf" of /etc/mysql/conf.d. The plugin
 * ships one, as a compose config rather than a bind mount, so its content lives
 * in the generated compose file and there is no host path to create.
 */
final class MysqlConfigurationTest extends SnapshotTestCase
{
    /**
     * @return array<string, mixed>
     */
    private function build(ServiceInterface $service): array
    {
        return $service->updateCompose($this->fixedContext(), new ComposeBuilder())->toArray();
    }

    public function testNoConfigurationShipsNothing(): void
    {
        $compose = $this->build(new MySQLService());

        static::assertArrayNotHasKey('configs', $compose);
        static::assertArrayNotHasKey('configs', $compose['services']['mysql']);
    }

    public function testSettingsBecomeAMysqldSection(): void
    {
        $compose = $this->build(
            (new MySQLService())
                ->withSetting('max_connections', 500)
                ->withSetting('innodb_buffer_pool_size', '1G')
                ->withSetting('slow_query_log', true)
                ->withSetting('performance_schema', false)
                // A flag that takes no value at all.
                ->withSetting('skip-name-resolve')
        );

        static::assertSame(
            <<<'CNF'
                # This file is generated by Castor. Do not edit it manually.
                [mysqld]
                max_connections = 500
                innodb_buffer_pool_size = 1G
                slow_query_log = ON
                performance_schema = OFF
                skip-name-resolve

                CNF,
            $compose['configs']['mysql-config']['content'],
        );

        static::assertSame(
            [['source' => 'mysql-config', 'target' => '/etc/mysql/conf.d/mysql.cnf']],
            $compose['services']['mysql']['configs'],
        );
    }

    public function testRawConfigurationIsAppended(): void
    {
        $compose = $this->build(
            (new MySQLService())
                ->withSetting('max_connections', 500)
                ->withConfiguration("[client]\ndefault-character-set = utf8mb4")
        );

        static::assertSame(
            <<<'CNF'
                # This file is generated by Castor. Do not edit it manually.
                [mysqld]
                max_connections = 500

                [client]
                default-character-set = utf8mb4

                CNF,
            $compose['configs']['mysql-config']['content'],
        );
    }

    public function testConfigurationFileIsReadAtGenerationTime(): void
    {
        $path = tempnam(sys_get_temp_dir(), 'cnf');
        \assert($path !== false);
        file_put_contents($path, "[mysqld]\nsql_mode = STRICT_ALL_TABLES\n");

        try {
            $compose = $this->build((new MySQLService())->withConfigurationFile($path));
        } finally {
            unlink($path);
        }

        static::assertStringContainsString('sql_mode = STRICT_ALL_TABLES', $compose['configs']['mysql-config']['content']);
    }

    /**
     * Silently ignoring a mistyped path would leave the server unconfigured
     * with nothing to show for it.
     */
    public function testAMissingConfigurationFileIsReported(): void
    {
        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('/nowhere/my.cnf');

        (new MySQLService())->withConfigurationFile('/nowhere/my.cnf');
    }

    public function testMariadbTakesTheSameConfiguration(): void
    {
        $compose = $this->build((new MariaDBService())->withSetting('max_connections', 500));

        static::assertStringContainsString('max_connections = 500', $compose['configs']['mariadb-config']['content']);
        static::assertSame(
            [['source' => 'mariadb-config', 'target' => '/etc/mysql/conf.d/mariadb.cnf']],
            $compose['services']['mariadb']['configs'],
        );
    }

    /**
     * Two instances must not overwrite each other's configuration.
     */
    public function testTheConfigurationIsNamedAfterTheService(): void
    {
        $compose = $this->build(
            (new MySQLService())->withName('reporting')->withSetting('max_connections', 500)
        );

        static::assertArrayHasKey('reporting-config', $compose['configs']);
        static::assertSame(
            [['source' => 'reporting-config', 'target' => '/etc/mysql/conf.d/reporting.cnf']],
            $compose['services']['reporting']['configs'],
        );
    }
}
