<?php

declare(strict_types=1);

namespace Castor\Docker\Tests\Unit\Service;

use Castor\Docker\Service\BinaryRunService;
use Castor\Docker\Service\Builder\ComposeBuilder;
use Castor\Docker\Service\ExtensionInstaller;
use Castor\Docker\Service\ClickhouseService;
use Castor\Docker\Service\ElasticsearchService;
use Castor\Docker\Service\GoBuilder;
use Castor\Docker\Service\GoService;
use Castor\Docker\Service\MailpitService;
use Castor\Docker\Service\MariaDBService;
use Castor\Docker\Service\MySQLService;
use Castor\Docker\Service\NodeService;
use Castor\Docker\Service\PHPService;
use Castor\Docker\Service\PhpMode;
use Castor\Docker\Service\PostgresService;
use Castor\Docker\Service\RabbitMQService;
use Castor\Docker\Service\RedirectionioAgentService;
use Castor\Docker\Service\RedisService;
use Castor\Docker\Service\RustBuilder;
use Castor\Docker\Service\RustService;
use Castor\Docker\Service\ServiceInterface;
use Castor\Docker\Service\SymfonyService;
use Castor\Docker\Tests\SnapshotTestCase;

/**
 * Freezes the compose configuration generated by each service. A failure here
 * means the generated compose.generated.yaml changed for every user of the
 * plugin: review the diff, then regenerate with UPDATE_SNAPSHOTS=1.
 */
final class ServiceComposeSnapshotTest extends SnapshotTestCase
{
    /**
     * @return array<string, mixed>
     */
    private function build(ServiceInterface ...$services): array
    {
        $builder = new ComposeBuilder();

        foreach ($services as $service) {
            $builder = $service->updateCompose($this->fixedContext(), $builder);
        }

        return $builder->toArray();
    }

    public function testPostgres(): void
    {
        $this->assertMatchesYamlSnapshot($this->build(new PostgresService()));
    }

    public function testMysql(): void
    {
        $this->assertMatchesYamlSnapshot($this->build(new MySQLService()));
    }

    public function testMariadb(): void
    {
        $this->assertMatchesYamlSnapshot($this->build(new MariaDBService()));
    }

    public function testRedis(): void
    {
        $this->assertMatchesYamlSnapshot($this->build(new RedisService()));
    }

    public function testRabbitmq(): void
    {
        $this->assertMatchesYamlSnapshot($this->build(new RabbitMQService()));
    }

    public function testElasticsearch(): void
    {
        $this->assertMatchesYamlSnapshot($this->build(new ElasticsearchService()));
    }

    public function testClickhouse(): void
    {
        $this->assertMatchesYamlSnapshot($this->build((new ClickhouseService())->withVersion('25.8')));
    }

    public function testRedirectionioAgent(): void
    {
        $this->assertMatchesYamlSnapshot($this->build(new RedirectionioAgentService()));
    }

    public function testRedirectionioAgentAsReverseProxy(): void
    {
        $app = (new PHPService('app'))->withDirectory('/project/app');
        $api = (new RustService('api'))->withVersion('1.90')->withDirectory('/project/api');

        $agent = (new RedirectionioAgentService())
            ->withProjectKey('default-key')
            ->addReverseProxy('app.demo.test', $app)
            ->addReverseProxy('legacy.demo.test', $app, 'legacy-key')
            ->addReverseProxy('api.demo.test', $api, port: 8080)
        ;

        $this->assertMatchesYamlSnapshot($this->build($app, $api, $agent));
    }

    public function testGo(): void
    {
        $this->assertMatchesYamlSnapshot($this->build(
            (new GoService('api'))->withVersion('1.25')->withDirectory('/project/api')->withDomain('api.demo.test'),
        ));
    }

    public function testRust(): void
    {
        $this->assertMatchesYamlSnapshot($this->build(
            (new RustService('api'))->withVersion('1.90')->withDirectory('/project/api')->withDomain('api.demo.test'),
        ));
    }

    public function testNode(): void
    {
        $this->assertMatchesYamlSnapshot($this->build(
            (new NodeService('front'))->withVersion('24')->withDirectory('/project/front')->withDomain('front.demo.test'),
        ));
    }

    /**
     * The infrastructure services name themselves, so the same one can be
     * registered twice. Everything they generate — the compose service, the
     * named volumes, the routed domain, the companion containers — has to be
     * derived from that name, or the second instance would collide with the
     * first.
     */
    public function testDuplicatedServices(): void
    {
        $this->assertMatchesYamlSnapshot($this->build(
            new PostgresService(),
            (new PostgresService())->withName('analytics'),
            new RedisService(),
            (new RedisService())->withName('sessions'),
            new ElasticsearchService(),
            (new ElasticsearchService())->withName('logs'),
            (new ClickhouseService())->withVersion('25.8')->withName('events'),
        ));
    }

    public function testRenamedServicesReferenceThemselvesInTheirDsn(): void
    {
        static::assertStringContainsString(
            '@analytics:5432/',
            (new PostgresService())->withName('analytics')->getDatabaseURL(),
        );
        static::assertStringContainsString(
            '@reporting:3306/',
            (new MySQLService())->withName('reporting')->getDatabaseURL(),
        );
        static::assertSame(
            'smtp://smtp-catcher:1025',
            (new MailpitService())->withName('smtp-catcher')->getMailerDSN(),
        );
    }

    public function testRustWithTargetAndWorkingDirectory(): void
    {
        $this->assertMatchesYamlSnapshot($this->build(
            (new RustService('agent'))
                ->withVersion('1.90')
                // The repository root is mounted, cargo runs in the crate, and
                // the musl target moves the binary out of target/debug/.
                ->withDirectory('/project')
                ->withWorkingDirectory('agent/agent-application')
                ->withTarget('x86_64-unknown-linux-musl')
                ->withRunCommand(['--listen', '0.0.0.0:18089'])
                ->addRustupTarget('x86_64-unknown-linux-musl')
                ->addRustupToolchain('nightly', ['rustfmt']),
        ));
    }

    /**
     * The monorepo shape: one compiler container per language, one runtime
     * container per binary, and two PHP applications sharing a single builder.
     */
    public function testMonorepo(): void
    {
        $rust = (new RustBuilder('rust-builder'))
            ->withVersion('1.94.0')
            ->withDirectory('/project')
            ->addRustupTarget('x86_64-unknown-linux-musl')
            ->withApp('agent/agent-application', target: 'x86_64-unknown-linux-musl')
            ->withApp('server/log-injector')
        ;

        $go = (new GoBuilder('go-builder'))
            ->withVersion('1.25')
            ->withDirectory('/project')
            ->withApp('server/exporter')
        ;

        $backend = (new SymfonyService('backend'))
            ->withDirectory('/project')
            ->withWorkingDirectory('server/backend')
            ->withDomain('backend.demo.test')
        ;

        $this->assertMatchesYamlSnapshot($this->build(
            $rust,
            $go,
            (new BinaryRunService('agent', 'agent/target/x86_64-unknown-linux-musl/debug/agent-application'))
                ->withBuilder($rust, 'agent/agent-application')
                ->withRunCommand(['--listen', '0.0.0.0:18089'])
                ->withDomain('agent.demo.test'),
            (new BinaryRunService('log-injector', 'server/target/debug/log-injector'))
                ->withBuilder($rust, 'server/log-injector'),
            (new BinaryRunService('exporter', 'server/exporter/exporter'))
                ->withBuilder($go, 'server/exporter'),
            $backend,
            // The second application generates no builder container of its own.
            (new SymfonyService('demo'))
                ->withDirectory('/project')
                ->withWorkingDirectory('server/demo')
                ->withSharedBuilder($backend)
                ->withDomain('demo.demo.test'),
        ));
    }

    public function testBinaryRunServiceWithoutBuilder(): void
    {
        $this->assertMatchesYamlSnapshot($this->build(
            (new BinaryRunService('agent', 'bin/agent'))
                ->withDirectory('/project')
                ->withImage('debian:13-slim'),
        ));
    }

    /**
     * A consumer given "--time-limit" exits successfully when it reaches it, so
     * without a policy the container stays down until the next "docker:up" —
     * and "on-failure" would not bring it back either, since the exit was a
     * success.
     */
    public function testWorkerRestartPolicy(): void
    {
        $compose = $this->build(
            (new PHPService('app'))
                ->withDirectory('/project')
                ->addWorker('scheduler', 'php bin/console schedule:run')
                ->addWorker('messenger', 'php bin/console messenger:consume async --time-limit=3600', 'unless-stopped'),
        );

        static::assertArrayNotHasKey('restart', $compose['services']['app-worker-scheduler']);
        static::assertSame('unless-stopped', $compose['services']['app-worker-messenger']['restart']);
    }

    /**
     * Nothing watches a binary that exits, so a restart policy is the only
     * thing bringing it back — but it stays opt-in, since it also fights a
     * deliberate "docker:stop" when set to "always".
     */
    public function testBinaryRunServiceRestartPolicy(): void
    {
        $compose = $this->build(
            (new BinaryRunService('agent', 'bin/agent'))->withDirectory('/project')->withImage('alpine:3'),
        );
        static::assertArrayNotHasKey('restart', $compose['services']['agent']);

        $compose = $this->build(
            (new BinaryRunService('agent', 'bin/agent'))->withDirectory('/project')->withImage('alpine:3')->withRestart(),
        );
        static::assertSame('on-failure', $compose['services']['agent']['restart']);

        $compose = $this->build(
            (new BinaryRunService('agent', 'bin/agent'))->withDirectory('/project')->withImage('alpine:3')->withRestart('unless-stopped'),
        );
        static::assertSame('unless-stopped', $compose['services']['agent']['restart']);
    }

    public function testPhpMinimal(): void
    {
        $this->assertMatchesYamlSnapshot($this->build(
            (new PHPService('app'))->withDirectory('/project/app'),
        ));
    }

    public function testPhpFpmMode(): void
    {
        $this->assertMatchesYamlSnapshot($this->build(
            (new PHPService('app'))->withDirectory('/project/app')->withMode(PhpMode::Fpm),
        ));
    }

    public function testPhpWithExtensions(): void
    {
        $this->assertMatchesYamlSnapshot($this->build(
            (new PHPService('app'))
                ->withDirectory('/project/app')
                ->addExtension('redis')
                ->addExtension('amqp'),
        ));
    }

    public function testPhpWithPieExtensions(): void
    {
        $this->assertMatchesYamlSnapshot($this->build(
            (new PHPService('app'))
                ->withDirectory('/project/app')
                ->addExtension('snmp', ['libsnmp-dev'])
                ->addExtension('xdebug/xdebug:^3.5', installer: ExtensionInstaller::Pie)
                ->addExtension('php/kafka', ['librdkafka-dev'], ExtensionInstaller::Pie),
        ));
    }

    public function testPhpWithFrankenPhpWorkerMode(): void
    {
        $this->assertMatchesYamlSnapshot($this->build(
            (new PHPService('app'))
                ->withDirectory('/project/app')
                ->withFrankenPhpWorkerMode('public/index.php', num: 4),
        ));
    }

    public function testPhpFullyConfigured(): void
    {
        $postgres = new PostgresService();

        $php = (new PHPService('app'))
            ->withDirectory('/project/app')
            ->withVersion('8.4')
            ->withDatabaseService($postgres)
            ->withDomain('app.demo.test', 'demo.test')
            ->withHttpAccess()
            ->addWorker('messenger', 'php bin/console messenger:consume async')
            ->addWorker('scheduler', 'php bin/console schedule:run')
        ;

        $this->assertMatchesYamlSnapshot($this->build($postgres, $php));
    }

    public function testPhpWithMailerDependsOnServiceStarted(): void
    {
        $mailer = new MailpitService();

        $compose = $this->build(
            $mailer,
            (new PHPService('app'))
                ->withDirectory('/project/app')
                ->withMailerService($mailer)
                ->addWorker('messenger', 'php bin/console messenger:consume async'),
        );

        static::assertSame('service_started', $compose['services']['app']['depends_on']['mailpit']['condition']);
        static::assertSame('service_started', $compose['services']['app-builder']['depends_on']['mailpit']['condition']);
        static::assertSame('service_started', $compose['services']['app-worker-messenger']['depends_on']['mailpit']['condition']);
    }

    public function testSymfonyWithMysql(): void
    {
        $mysql = new MySQLService();

        $symfony = (new SymfonyService('app'))
            ->withDirectory('/project/app')
            ->withDatabaseService($mysql)
            ->withDomain('app.demo.test')
        ;

        $this->assertMatchesYamlSnapshot($this->build($mysql, $symfony));
    }
}
