<?php

declare(strict_types=1);

namespace Castor\Docker\Tests\Unit\Service;

use Castor\Docker\Service\Builder\ComposeBuilder;
use Castor\Docker\Service\ClickhouseService;
use Castor\Docker\Service\ElasticsearchService;
use Castor\Docker\Service\GoService;
use Castor\Docker\Service\MariaDBService;
use Castor\Docker\Service\MySQLService;
use Castor\Docker\Service\PHPService;
use Castor\Docker\Service\PhpMode;
use Castor\Docker\Service\PostgresService;
use Castor\Docker\Service\RabbitMQService;
use Castor\Docker\Service\RedirectionioAgentService;
use Castor\Docker\Service\RedisService;
use Castor\Docker\Service\RustService;
use Castor\Docker\Service\ServiceInterface;
use Castor\Docker\Service\SymfonyService;
use Castor\Docker\Tests\SnapshotTestCase;

/**
 * Freezes the compose configuration generated by each service. A failure here
 * means the generated compose.generated.yaml changed for every user of the
 * plugin: review the diff, then regenerate with UPDATE_SNAPSHOTS=1.
 */
final class ServiceComposeSnapshotTest extends SnapshotTestCase
{
    /**
     * @return array<string, mixed>
     */
    private function build(ServiceInterface ...$services): array
    {
        $builder = new ComposeBuilder();

        foreach ($services as $service) {
            $builder = $service->updateCompose($this->fixedContext(), $builder);
        }

        return $builder->toArray();
    }

    public function testPostgres(): void
    {
        $this->assertMatchesYamlSnapshot($this->build(new PostgresService()));
    }

    public function testMysql(): void
    {
        $this->assertMatchesYamlSnapshot($this->build(new MySQLService()));
    }

    public function testMariadb(): void
    {
        $this->assertMatchesYamlSnapshot($this->build(new MariaDBService()));
    }

    public function testRedis(): void
    {
        $this->assertMatchesYamlSnapshot($this->build(new RedisService()));
    }

    public function testRabbitmq(): void
    {
        $this->assertMatchesYamlSnapshot($this->build(new RabbitMQService()));
    }

    public function testElasticsearch(): void
    {
        $this->assertMatchesYamlSnapshot($this->build(new ElasticsearchService()));
    }

    public function testClickhouse(): void
    {
        $this->assertMatchesYamlSnapshot($this->build((new ClickhouseService())->withVersion('25.8')));
    }

    public function testRedirectionioAgent(): void
    {
        $this->assertMatchesYamlSnapshot($this->build(new RedirectionioAgentService()));
    }

    public function testRedirectionioAgentAsReverseProxy(): void
    {
        $app = (new PHPService('app'))->withDirectory('/project/app');
        $api = (new RustService('api'))->withVersion('1.90')->withDirectory('/project/api');

        $agent = (new RedirectionioAgentService())
            ->withProjectKey('default-key')
            ->addReverseProxy('app.demo.test', $app)
            ->addReverseProxy('legacy.demo.test', $app, 'legacy-key')
            ->addReverseProxy('api.demo.test', $api, port: 8080)
        ;

        $this->assertMatchesYamlSnapshot($this->build($app, $api, $agent));
    }

    public function testGo(): void
    {
        $this->assertMatchesYamlSnapshot($this->build(
            (new GoService('api'))->withVersion('1.25')->withDirectory('/project/api')->withDomain('api.demo.test'),
        ));
    }

    public function testRust(): void
    {
        $this->assertMatchesYamlSnapshot($this->build(
            (new RustService('api'))->withVersion('1.90')->withDirectory('/project/api')->withDomain('api.demo.test'),
        ));
    }

    public function testPhpMinimal(): void
    {
        $this->assertMatchesYamlSnapshot($this->build(
            (new PHPService('app'))->withDirectory('/project/app'),
        ));
    }

    public function testPhpFpmMode(): void
    {
        $this->assertMatchesYamlSnapshot($this->build(
            (new PHPService('app'))->withDirectory('/project/app')->withMode(PhpMode::Fpm),
        ));
    }

    public function testPhpWithExtensions(): void
    {
        $this->assertMatchesYamlSnapshot($this->build(
            (new PHPService('app'))
                ->withDirectory('/project/app')
                ->addExtension('redis')
                ->addExtension('amqp'),
        ));
    }

    public function testPhpWithFrankenPhpWorkerMode(): void
    {
        $this->assertMatchesYamlSnapshot($this->build(
            (new PHPService('app'))
                ->withDirectory('/project/app')
                ->withFrankenPhpWorkerMode('public/index.php', num: 4),
        ));
    }

    public function testPhpFullyConfigured(): void
    {
        $postgres = new PostgresService();

        $php = (new PHPService('app'))
            ->withDirectory('/project/app')
            ->withVersion('8.4')
            ->withDatabaseService($postgres)
            ->withDomain('app.demo.test', 'demo.test')
            ->withHttpAccess()
            ->addWorker('messenger', 'php bin/console messenger:consume async')
            ->addWorker('scheduler', 'php bin/console schedule:run')
        ;

        $this->assertMatchesYamlSnapshot($this->build($postgres, $php));
    }

    public function testSymfonyWithMysql(): void
    {
        $mysql = new MySQLService();

        $symfony = (new SymfonyService('app'))
            ->withDirectory('/project/app')
            ->withDatabaseService($mysql)
            ->withDomain('app.demo.test')
        ;

        $this->assertMatchesYamlSnapshot($this->build($mysql, $symfony));
    }
}
