<?php

declare(strict_types=1);

namespace Castor\Docker\Tests\Unit\Service;

use Castor\Docker\Service\ClickhouseService;
use Castor\Docker\Service\GoService;
use Castor\Docker\Service\MariaDBService;
use Castor\Docker\Service\MySQLService;
use Castor\Docker\Service\PHPService;
use Castor\Docker\Service\PostgresService;
use Castor\Docker\Service\ServiceInterface;
use Castor\Docker\Service\SymfonyService;
use Castor\Docker\Service\TraefikRouterService;
use PHPUnit\Framework\TestCase;

/**
 * Pins the CLI surface generated by each service, so renaming or removing a
 * task is a deliberate, visible change.
 */
final class TaskRegistrationTest extends TestCase
{
    /**
     * @return list<string>
     */
    private function taskNames(ServiceInterface $service): array
    {
        $names = [];

        foreach ($service->getTasks() as $task) {
            $asTask = $task['task'];
            $names[] = ($asTask->namespace !== null && $asTask->namespace !== '' ? $asTask->namespace . ':' : '') . $asTask->name;
        }

        return $names;
    }

    public function testPhpServiceTasks(): void
    {
        self::assertSame(
            ['app:bash', 'app:install', 'app:composer', 'app:qa:phpstan', 'app:qa:cs', 'app:qa:rector'],
            $this->taskNames(new PHPService(name: 'app')),
        );
    }

    public function testSymfonyServiceTasks(): void
    {
        self::assertSame(
            [
                'app:bash', 'app:install', 'app:composer', 'app:qa:phpstan', 'app:qa:cs', 'app:qa:rector',
                'app:cache-clear', 'app:cache-warmup', 'app:db:fixtures', 'app:db:migrate', 'app:symfony', 'app:qa:twig-cs',
            ],
            $this->taskNames(new SymfonyService(name: 'app')),
        );
    }

    public function testDatabaseServicesTasks(): void
    {
        self::assertSame(['db:psql'], $this->taskNames(new PostgresService()));
        self::assertSame(['db:mysql'], $this->taskNames(new MySQLService()));
        self::assertSame(['db:mariadb'], $this->taskNames(new MariaDBService()));
        self::assertSame(['db:clickhouse'], $this->taskNames(new ClickhouseService('25.8')));
    }

    public function testGoServiceTasks(): void
    {
        self::assertSame(['api:build', 'api:restart', 'api:watch'], $this->taskNames(new GoService('api', '1.25')));
    }

    public function testTraefikRouterTasks(): void
    {
        self::assertSame(
            ['router:generate-certificates', 'router:enable', 'router:disable'],
            $this->taskNames(new TraefikRouterService()),
        );
    }
}
