import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// Generated by Castor: what a Vite dev server needs to be served from a
// container, behind the HTTPS router.
export default defineConfig({
    plugins: [react()],
    server: {
        // Vite binds to localhost by default, which answers only inside the
        // container — the router gets a connection refused and returns 502.
        host: '0.0.0.0',
        port: __PORT__,
__HMR__    },
})
