<?php

declare(strict_types=1);

namespace Castor\Docker\Service\Behaviour;

use Castor\Docker\Service\Builder\ComposeBuilder;
use Castor\Docker\Service\Builder\ServiceBuilder;

/**
 * Server configuration for the MySQL-family databases, which read every
 * "*.cnf" of /etc/mysql/conf.d on top of their built-in defaults.
 *
 * The three sources are merged into a single file, shipped as a compose config
 * rather than as a bind mount: the content ends up in the generated compose
 * file, so there is no host path to create, nothing to keep in sync, and no
 * file whose permissions the server might refuse.
 *
 *     (new MySQLService())
 *         ->withSetting('max_connections', 500)
 *         ->withSetting('skip-name-resolve')          // a flag, no value
 *         ->withConfigurationFile(__DIR__ . '/docker/my.cnf')
 */
trait HasMysqlConfiguration
{
    /** Read in alphabetical order, so the generated file lands last. */
    protected const CONFIGURATION_DIRECTORY = '/etc/mysql/conf.d';

    /** @var array<string, string|int|float|bool|null> */
    protected array $settings = [];

    /** @var list<string> */
    protected array $configurations = [];

    /**
     * Set a server variable of the [mysqld] section. A null value writes the
     * bare option name, for the flags that take none.
     */
    public function withSetting(string $name, string|int|float|bool|null $value = null): static
    {
        $this->settings[$name] = $value;

        return $this;
    }

    /**
     * @param array<string, string|int|float|bool|null> $settings
     */
    public function withSettings(array $settings): static
    {
        foreach ($settings as $name => $value) {
            $this->withSetting($name, $value);
        }

        return $this;
    }

    /**
     * Append a raw configuration block, sections included — for what
     * withSetting() cannot express.
     */
    public function withConfiguration(string $content): static
    {
        $this->configurations[] = $content;

        return $this;
    }

    /**
     * Append the content of a configuration file of your project.
     *
     * It is read when the compose file is generated, not mounted, so the file
     * never has to exist inside the container — and a typo in the path is
     * reported here instead of silently leaving the server unconfigured.
     */
    public function withConfigurationFile(string $path): static
    {
        if (!is_file($path)) {
            throw new \InvalidArgumentException(\sprintf('The configuration file "%s" does not exist.', $path));
        }

        $content = file_get_contents($path);

        if (false === $content) {
            throw new \RuntimeException(\sprintf('The configuration file "%s" could not be read.', $path));
        }

        return $this->withConfiguration($content);
    }

    /**
     * Mount the generated configuration, when there is anything to mount.
     */
    protected function applyConfiguration(ComposeBuilder $builder, ServiceBuilder $service): void
    {
        $configuration = $this->generateConfiguration();

        if (null === $configuration) {
            return;
        }

        $name = $this->getName() . '-config';

        $builder->config($name, $configuration);
        // The server reads its configuration once, at boot: without the digest
        // compose would leave the container running with the previous one.
        $service->config($name, static::CONFIGURATION_DIRECTORY . '/' . $this->getName() . '.cnf', recreateOnChange: true);
    }

    protected function generateConfiguration(): ?string
    {
        if (!$this->settings && !$this->configurations) {
            return null;
        }

        $lines = ['# This file is generated by Castor. Do not edit it manually.'];

        if ($this->settings) {
            $lines[] = '[mysqld]';

            foreach ($this->settings as $name => $value) {
                $lines[] = null === $value ? $name : $name . ' = ' . $this->formatSetting($value);
            }

            $lines[] = '';
        }

        foreach ($this->configurations as $configuration) {
            $lines[] = trim($configuration, "\n");
            $lines[] = '';
        }

        return implode("\n", $lines);
    }

    protected function formatSetting(string|int|float|bool $value): string
    {
        if (\is_bool($value)) {
            return $value ? 'ON' : 'OFF';
        }

        return (string) $value;
    }

    abstract public function getName(): string;
}
