# syntax=ghcr.io/castor-php/twig-dockerfile:latest
{% extends '@original/Dockerfile' %}

{% block frontend %}
{% endblock %}
{% block worker %}
{% endblock %}
{% block builder %}
{% endblock %}

{% block php_extensions %}
    "php{{ php_version }}-xdebug" \
{% endblock %}