# syntax=castor/twig-dockerfile:latest
FROM ubuntu:22.04

# Install necessary packages
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update
{% for package in packages %}
RUN apt install -y {{ package }}
{% endfor %}