<?php

namespace Castor\Docker;

use Castor\Attribute\AsListener;
use Castor\Console\Command\TaskCommand;
use Castor\Container;
use Castor\Context;
use Castor\Descriptor\TaskDescriptor;
use Castor\Docker\Event\RegisterServiceEvent;
use Castor\Docker\Service\TraefikRouterService;
use Castor\Event\AfterBootEvent;
use Castor\ExpressionLanguage;
use Symfony\Component\Process\Process;

use function Castor\context;
use function Castor\get_cache;
use function Castor\run;
use function Castor\variable;
use function Castor\yaml_dump;

/**
 * @return list<string>
 */
function get_default_profiles(): array
{
    $profiles = ['default'];
    $routerCache = get_cache()->getItem('infrastructure.router.enabled');

    if ($routerCache->isHit() && $routerCache->get() === true) {
        $profiles[] = 'router';
    }

    return $profiles;
}

/**
 * @param list<string> $subCommand
 * @param list<string> $profiles
 */
function docker_compose(array $subCommand, ?Context $c = null, array $profiles = []): Process
{
    $c ??= context();
    $profiles = $profiles ?: get_default_profiles();

    $c = $c
        ->withTimeout(null)
        ->withEnvironment([
            'PHP_VERSION' => variable('php_version'),
        ])
    ;

    $command = [
        'docker',
        'compose',
    ];

    foreach ($profiles as $profile) {
        $command[] = '--profile';
        $command[] = $profile;
    }

    $command[] = '-f';
    $command[] = $c->workingDirectory . '/compose.yaml';

    $command[] = '-f';
    $command[] = $c->workingDirectory . '/compose.override.yaml';

    $command = array_merge($command, $subCommand);

    return run($command, context: $c);
}

function docker_compose_run(
    string $runCommand,
    string $service,
    ?Context $c = null,
    bool $noDeps = true,
    ?string $workDir = null,
    bool $portMapping = false,
): Process {
    $command = [
        'run',
        '--rm',
    ];

    if ($noDeps) {
        $command[] = '--no-deps';
    }

    if ($portMapping) {
        $command[] = '--service-ports';
    }

    if (null !== $workDir) {
        $command[] = '-w';
        $command[] = $workDir;
    }

    $command[] = $service;
    $command[] = '/bin/sh';
    $command[] = '-c';
    $command[] = "exec {$runCommand}";

    return docker_compose($command, c: $c);
}

function docker_exit_code(
    string $runCommand,
    string $service = 'builder',
    ?Context $c = null,
    bool $noDeps = true,
    ?string $workDir = null,
    bool $portMapping = false,
): int {
    $c = ($c ?? context())->withAllowFailure();

    $process = docker_compose_run(
        runCommand: $runCommand,
        service: $service,
        c: $c,
        noDeps: $noDeps,
        workDir: $workDir,
    );

    return $process->getExitCode() ?? 0;
}

#[AsListener(AfterBootEvent::class)]
function initialize(AfterBootEvent $afterBootEvent): void
{
    $c = context();
    $container = Container::get();
    $dispatcher = $container->eventDispatcher;

    $event = new RegisterServiceEvent();
    $event->addService(new TraefikRouterService());

    $dispatcher->dispatch($event);

    $compose = [
        'name' => $c['project_name'] ?? 'project',
        'volumes' => [],
        'services' => [],
    ];

    $userId = \function_exists('posix_geteuid') ? posix_geteuid() : getmyuid();
    $c = $c->withData(['user_id' => $userId]);

    foreach ($event->services as $name => $service) {
        $compose = $service->updateCompose($c, $compose);
    }

    $yamlContent = yaml_dump($compose, inline: 5);

    file_put_contents(
        $c->workingDirectory . '/compose.yaml',
        <<<YAML
        # This file is generated by Castor. Do not edit it manually.
        
        YAML
    );
    file_put_contents($c->workingDirectory . '/compose.yaml', $yamlContent, FILE_APPEND);

    // create override file if not exists
    $overrideFile = $c->workingDirectory . '/compose.override.yaml';
    if (!file_exists($overrideFile)) {
        file_put_contents(
            $overrideFile,
            <<<YAML
            # This file is for your local overrides. It is not generated by Castor.
            YAML
        );
    }

    // Handle tasks for each eservice
    $expressionLanguage = new ExpressionLanguage($container->contextRegistry);

    foreach ($event->services as $service) {
        foreach ($service->getTasks() as $task) {
            $closure = $task['function'];
            $asTask = $task['task'];
            $function = new \ReflectionFunction($closure);
            $descriptor = new TaskDescriptor($asTask, $function);
            $command = new TaskCommand($descriptor, $expressionLanguage, $container->eventDispatcher, $container->contextRegistry, $container->slugger, $container->fs);

            $container->application->add($command);
        }
    }
}
