<?php

declare(strict_types=1);

namespace Castor\Docker;

use Castor\Attribute\AsTask;
use Castor\Context;
use Symfony\Component\Process\ExecutableFinder;

use function Castor\capture;
use function Castor\context;
use function Castor\fs;
use function Castor\get_cache;
use function Castor\io;
use function Castor\run;
use function Castor\yaml_dump;

/**
 * The name of the router, used for its compose project, its container and —
 * through compose — its own network ("<name>_default").
 */
function get_router_name(): string
{
    return 'castor-docker-router';
}

/**
 * Get the path to the global router directory.
 */
function get_router_directory(): string
{
    return $_SERVER['HOME'] . '/.castor/docker/router';
}

/**
 * Get the path to the global router compose file.
 */
function get_router_compose_file(): string
{
    return get_router_directory() . '/compose.yaml';
}

/**
 * Get the path to the router certificate directory, holding the optional
 * mkcert CA used to mint locally-trusted certificates.
 *
 * The router is global, so this must not be derived from any project path: an
 * project-relative one would be resolved against the project directory when
 * written from PHP, but against the router directory when mounted by compose.
 */
function get_router_certs_directory(): string
{
    return get_router_directory() . '/certs';
}

/**
 * The upstream router image. The base Caddyfile is passed as a compose config
 * rather than baked in with a Dockerfile, so enabling the router never depends
 * on a project's vendor directory being present.
 */
function get_router_image(): string
{
    return 'lucaslorentz/caddy-docker-proxy:2.13.1-alpine';
}

/**
 * The socket of the Docker daemon the projects run on, which the router has to
 * watch to see their "caddy.*" labels.
 *
 * Not always /var/run/docker.sock: a CI job installing a daemon of its own, a
 * rootless daemon and Colima all put theirs somewhere else, and the daemon of
 * /var/run/docker.sock may then be a *different* one — where the containers of
 * the project do not exist. The router would come up, see no label at all and
 * serve nothing, refusing the connections on 443 rather than failing outright.
 *
 * DOCKER_SOCKET_PATH is the convention such setups export; DOCKER_HOST is what
 * the Docker CLI itself reads, and only a unix one can be bind-mounted.
 */
function get_docker_socket_path(): string
{
    $socket = $_SERVER['DOCKER_SOCKET_PATH'] ?? null;

    if (\is_string($socket) && '' !== $socket) {
        return $socket;
    }

    $host = $_SERVER['DOCKER_HOST'] ?? null;

    if (\is_string($host) && str_starts_with($host, 'unix://')) {
        return substr($host, \strlen('unix://'));
    }

    return '/var/run/docker.sock';
}

/**
 * Whether the router may be started and stopped along with the projects.
 *
 * On by default: a project routing a domain cannot be reached without the
 * router, and remembering to start it by hand is a step that only shows up as a
 * "connection refused" much later. The environment variable wins over the
 * context, so a CI job, a script or a single shell can turn it off without
 * touching the project — anything the Docker CLI reads as a boolean is accepted.
 */
function is_router_autostart_enabled(?Context $c = null): bool
{
    $env = $_SERVER['CASTOR_DOCKER_ROUTER_AUTOSTART'] ?? null;

    if (\is_string($env) && '' !== $env) {
        $value = filter_var($env, \FILTER_VALIDATE_BOOL, \FILTER_NULL_ON_FAILURE);

        if (null !== $value) {
            return $value;
        }
    }

    $data = ($c ?? context())->data['router_autostart'] ?? null;

    if (\is_bool($data)) {
        return $data;
    }

    return true;
}

/**
 * Ensure the global router compose file exists and is up to date.
 */
function ensure_router_compose(): void
{
    // Create the router directories if they don't exist. The certificate one
    // is mounted by the router, so it must exist beforehand or Docker would
    // create it as root.
    fs()->mkdir([get_router_directory(), get_router_certs_directory()]);

    $yamlContent = yaml_dump(get_router_compose(), inline: 10);

    fs()->dumpFile(
        get_router_compose_file(),
        "# This file is automatically generated by Castor Docker Plugin\n"
        . "# Do not edit manually - it will be regenerated on router:enable\n\n"
        . $yamlContent
    );
}

/**
 * The compose definition of the router.
 *
 * @return array<string, mixed>
 */
function get_router_compose(): array
{
    $certsDir = get_router_certs_directory();

    // Read at generation time only: the content is embedded in the compose
    // file below, which therefore stays valid even if this plugin is removed.
    $caddyfile = file_get_contents(__DIR__ . '/Resources/router/Caddyfile');

    return [
        'name' => get_router_name(),
        'volumes' => [
            'router-data' => null,
        ],
        'configs' => [
            'caddyfile' => [
                'content' => $caddyfile,
            ],
        ],
        'services' => [
            'router' => [
                'image' => get_router_image(),
                'container_name' => get_router_name(),
                'restart' => 'unless-stopped',
                'environment' => [
                    'CADDY_DOCKER_CADDYFILE_PATH' => '/etc/caddy/Caddyfile',
                ],
                'configs' => [
                    [
                        'source' => 'caddyfile',
                        'target' => '/etc/caddy/Caddyfile',
                    ],
                ],
                'volumes' => [
                    // caddy-docker-proxy watches the Docker socket to build its
                    // configuration from the "caddy.*" labels of the services.
                    get_docker_socket_path() . ':/var/run/docker.sock',
                    // Persist issued certificates and the local CA between restarts.
                    'router-data:/data',
                    "{$certsDir}:/certs:cached",
                ],
                'ports' => [
                    '80:80',
                    '443:443',
                ],
                'labels' => [
                    'castor.managed' => 'true',
                    'castor.router' => 'true',
                ],
            ],
        ],
    ];
}

/**
 * Check if the global router is currently running.
 */
function is_router_running(): bool
{
    try {
        $output = capture(
            ['docker', 'ps', '--filter', 'name=' . get_router_name(), '--filter', 'status=running', '--format', '{{.Names}}'],
            context: context()->withQuiet()->withAllowFailure()
        );

        return trim($output) === get_router_name();
    } catch (\Throwable) {
        return false;
    }
}

/**
 * The projects the router is currently serving: the ones with a running
 * container carrying a "caddy" label.
 *
 * A routed container that compose did not create has no project to name, so its
 * own name stands for it — it is still something the router serves, and still a
 * reason to keep it up.
 *
 * @return list<string>
 */
function get_routed_projects(): array
{
    try {
        $found = capture(
            ['docker', 'ps', '--filter', 'label=caddy', '--format', '{{.Label "com.docker.compose.project"}}|{{.Names}}'],
            context: context()->withQuiet()->withAllowFailure()
        );
    } catch (\Throwable) {
        return [];
    }

    $projects = [];

    foreach (explode("\n", trim($found)) as $line) {
        if ('' === trim($line)) {
            continue;
        }

        [$project, $name] = array_pad(explode('|', trim($line), 2), 2, '');
        $projects[trim($project) ?: trim($name)] = true;
    }

    unset($projects['']);
    ksort($projects);

    return array_keys($projects);
}

/**
 * Create the router compose file, install the CA when mkcert is there, and
 * start the container — what both "docker:router:enable" and the autostart do.
 *
 * @return list<string> the networks of the already-running projects it joined
 */
function start_router(): array
{
    ensure_router_compose();

    $socket = get_docker_socket_path();

    // A router watching a socket that is not there sees no service of any
    // project, and answers nothing on 443 — with only "connection refused" on
    // the caller's side to go by. Say it here instead.
    if (!file_exists($socket)) {
        io()->warning([
            \sprintf('The Docker socket %s does not exist.', $socket),
            'The router builds its routes from the labels it reads there, so it will serve nothing at all.',
            'Set DOCKER_SOCKET_PATH to the socket of the daemon your projects run on.',
        ]);
    }

    install_certificate_authority();

    run(['docker', 'compose', '-f', get_router_compose_file(), 'up', '-d']);

    // Join the projects that are already running: "docker:up" only attaches the
    // router to its project network when the router is up at that time.
    $networks = connect_router_to_running_projects();

    $routerCache = get_cache()->getItem('infrastructure.router.enabled');
    $routerCache->set(true);
    get_cache()->save($routerCache);

    return $networks;
}

/**
 * Stop the router container. False when there is no compose file to stop it
 * with, which means it was never set up here.
 */
function stop_router(): bool
{
    $composeFile = get_router_compose_file();

    if (!file_exists($composeFile)) {
        return false;
    }

    run(['docker', 'compose', '-f', $composeFile, 'down']);

    $routerCache = get_cache()->getItem('infrastructure.router.enabled');
    $routerCache->set(false);
    get_cache()->save($routerCache);

    return true;
}

/**
 * Start the router on "docker:up", when the project needs it and it is not
 * already running.
 *
 * Called before compose starts the containers, because the project network is
 * joined right after and a router that is not up yet cannot join it.
 *
 * A project routing no domain never triggers this: it has nothing for the
 * router to serve, and does not have to pay for a container it does not use.
 */
function autostart_router(?Context $c = null): void
{
    $c ??= context();

    if (!is_router_autostart_enabled($c) || !get_project_urls($c) || is_router_running()) {
        return;
    }

    io()->comment('Starting the global Caddy router, which this project needs to serve its domains.');

    try {
        start_router();
    } catch (\Throwable $e) {
        // The project itself can still come up: it is only its domains that
        // will not answer, and saying so beats failing the whole task.
        io()->warning('Could not start the global router: ' . $e->getMessage());
        io()->note('Start it yourself with "castor docker:router:enable".');
    }
}

/**
 * Stop the router on "docker:stop" and "docker:destroy", once no project is
 * left for it to serve.
 *
 * However it was started: a router serving nothing is a container holding ports
 * 80 and 443 for no one, and the next project that needs it starts it again.
 * Turn the autostart off to keep one running for good.
 *
 * A project routing no domain leaves it alone: it never asked for the router,
 * so it has no business taking it away from the others.
 */
function autostop_router(?Context $c = null): void
{
    $c ??= context();

    if (!is_router_autostart_enabled($c) || !get_project_urls($c) || !is_router_running()) {
        return;
    }

    $projects = get_routed_projects();

    if ($projects) {
        io()->comment(\sprintf('Leaving the global Caddy router up, it still serves: %s.', implode(', ', $projects)));

        return;
    }

    io()->comment('Stopping the global Caddy router, no project needs it anymore.');

    try {
        stop_router();
    } catch (\Throwable $e) {
        io()->warning('Could not stop the global router: ' . $e->getMessage());
    }
}

/**
 * Install the mkcert certificate authority for locally-trusted certificates.
 */
function install_certificate_authority(): void
{
    $certsDir = get_router_certs_directory();
    $caddyDir = $certsDir . '/caddy';

    $mkcert = (new ExecutableFinder())->find('mkcert');

    if (!$mkcert) {
        io()->comment('mkcert is not installed: the router will use its own local CA (browsers will show a security warning). Install mkcert (https://github.com/FiloSottile/mkcert) for locally-trusted certificates.');

        return;
    }

    $caRoot = trim(capture(['mkcert', '-CAROOT']));

    if (!is_dir($caRoot) || !file_exists("{$caRoot}/rootCA.pem") || !file_exists("{$caRoot}/rootCA-key.pem")) {
        io()->warning('You must have the mkcert CA installed on your host with the "mkcert -install" command.');

        return;
    }

    fs()->mkdir($caddyDir);

    if (fs()->exists("{$certsDir}/rootCA.pem")) {
        fs()->remove("{$certsDir}/rootCA.pem");
    }

    if (fs()->exists("{$certsDir}/rootCA-key.pem")) {
        fs()->remove("{$certsDir}/rootCA-key.pem");
    }

    fs()->copy("{$caRoot}/rootCA.pem", "{$certsDir}/rootCA.pem", true);
    fs()->copy("{$caRoot}/rootCA-key.pem", "{$certsDir}/rootCA-key.pem", true);

    // Tell Caddy's internal issuer to sign on-demand certificates with the
    // mkcert root, which is already trusted by the host and its browsers.
    //
    // The mkcert root is created with "pathlen:0", so it may only sign leaf
    // certificates directly, not an intermediate CA. Caddy signs leaves with
    // its intermediate by default, so we point the intermediate at the mkcert
    // root as well: leaves are then signed straight from the mkcert root and
    // the chain stays valid (otherwise browsers reject it with a "path length
    // constraint exceeded" error).
    fs()->dumpFile("{$caddyDir}/ca.caddy", <<<'CADDY'
        pki {
            ca local {
                root {
                    cert /certs/rootCA.pem
                    key /certs/rootCA-key.pem
                }
                intermediate {
                    cert /certs/rootCA.pem
                    key /certs/rootCA-key.pem
                }
            }
        }
        CADDY);

    io()->comment('Using the mkcert CA for locally-trusted certificates.');
}

/**
 * Attach the router to a project network so it can reach that project's
 * services.
 *
 * Projects deliberately do not share a network: each keeps its own, and the
 * router — which is a member of all of them — is the only container with a foot
 * in several projects. Two projects exposing a service under the same name
 * therefore never collide in the Docker DNS. caddy-docker-proxy resolves
 * "{{upstreams}}" to container IPs rather than names, so it only needs to be
 * routable to them.
 *
 * A no-op when the router is not running, and when it is already a member.
 *
 * The project domains are passed as network aliases, so they also resolve to
 * the router through the Docker DNS. This is a complement to the extra_hosts
 * the generator writes (see add_project_extra_hosts()), which take precedence
 * as /etc/hosts always does — it is what makes the domains resolve when that
 * behaviour is turned off. Aliases are only applied when the router actually
 * joins: Docker keeps the ones it already has for a network it is a member of.
 *
 * @param list<string> $aliases
 */
function connect_router_to_network(string $network, array $aliases = []): void
{
    if (!is_router_running()) {
        return;
    }

    $command = ['docker', 'network', 'connect'];

    foreach ($aliases as $alias) {
        $command[] = '--alias';
        $command[] = $alias;
    }

    $command[] = $network;
    $command[] = get_router_name();

    run($command, context: context()->withQuiet()->withAllowFailure());
}

/**
 * Detach the router from a project network.
 *
 * Required before "docker compose down": Docker refuses to remove a network
 * that still has an endpoint, so leaving the router attached would leave a
 * dangling network behind and print an error.
 */
function disconnect_router_from_network(string $network): void
{
    if (!is_router_running()) {
        return;
    }

    run(
        ['docker', 'network', 'disconnect', $network, get_router_name()],
        context: context()->withQuiet()->withAllowFailure()
    );
}

/**
 * The networks the router is currently a member of.
 *
 * @return list<string>
 */
function get_router_networks(): array
{
    $found = trim(capture(
        ['docker', 'inspect', '-f', '{{range $k, $v := .NetworkSettings.Networks}}{{$k}}{{"\n"}}{{end}}', get_router_name()],
        context: context()->withQuiet()->withAllowFailure()
    ));

    return array_values(array_filter(array_map(trim(...), explode("\n", $found))));
}

/**
 * Attach the router to the networks of every already-running routed container.
 *
 * Enabling the router after the projects are up would otherwise route nothing
 * until the next "docker:up".
 *
 * @return list<string>
 */
function connect_router_to_running_projects(): array
{
    $ids = array_filter(explode("\n", trim(capture(
        ['docker', 'ps', '--filter', 'label=caddy', '--format', '{{.ID}}'],
        context: context()->withQuiet()->withAllowFailure()
    ))));

    $networks = [];

    foreach ($ids as $id) {
        $found = trim(capture(
            ['docker', 'inspect', '-f', '{{range $k, $v := .NetworkSettings.Networks}}{{$k}}{{"\n"}}{{end}}', $id],
            context: context()->withQuiet()->withAllowFailure()
        ));

        foreach (array_filter(explode("\n", $found)) as $network) {
            $networks[trim($network)] = true;
        }
    }

    unset($networks[get_router_name() . '_default']);

    foreach (array_keys($networks) as $network) {
        connect_router_to_network($network);
    }

    return array_keys($networks);
}

#[AsTask(name: 'enable', namespace: 'docker:router', description: 'Enable and start the global Caddy router')]
function router_enable(): void
{
    io()->title('Enabling Castor Docker Router');

    $networks = start_router();

    io()->comment('Router compose file created at: ' . get_router_compose_file());

    foreach ($networks as $network) {
        io()->comment(\sprintf('Joined the network of a running project: %s', $network));
    }

    io()->success('Router enabled and running!');
    io()->note([
        'The router is now running globally at http://localhost:80 and https://localhost:443',
        'All projects using castor-docker will automatically connect to this router',
        'Use "castor docker:router:disable" to stop the router',
    ]);
}

#[AsTask(name: 'disable', namespace: 'docker:router', description: 'Stop and disable the global Caddy router')]
function router_disable(): void
{
    io()->title('Disabling Castor Docker Router');

    if (!stop_router()) {
        io()->warning('Router compose file not found. Router may not be set up.');

        return;
    }

    io()->success('Router disabled');
    io()->note('Use "castor docker:router:enable" to start it again');

    if (is_router_autostart_enabled()) {
        io()->note('The next "castor docker:up" of a project routing a domain will start it again. Set "router_autostart" to false, or CASTOR_DOCKER_ROUTER_AUTOSTART=0, to keep it down.');
    }
}

#[AsTask(name: 'status', namespace: 'docker:router', description: 'Show the status of the global Caddy router')]
function router_status(): void
{
    $isRunning = is_router_running();
    $cacheItem = get_cache()->getItem('infrastructure.router.enabled');
    $isEnabled = $cacheItem->isHit() && $cacheItem->get() === true;
    $served = $isRunning ? get_routed_projects() : [];

    io()->title('Castor Docker Router Status');

    io()->definitionList(
        ['Status' => $isRunning ? '<fg=green>Running</>' : '<fg=red>Stopped</>'],
        ['Enabled in cache' => $isEnabled ? '<fg=green>Yes</>' : '<fg=yellow>No</>'],
        ['Autostart' => is_router_autostart_enabled() ? '<fg=green>On</>' : '<fg=yellow>Off</>'],
        ['Compose file' => file_exists(get_router_compose_file()) ? get_router_compose_file() : '<fg=red>Not found</>'],
        ['Container name' => get_router_name()],
        ['Ports' => '80:80, 443:443'],
        ['Joined networks' => $isRunning ? implode(', ', get_router_networks()) : '<fg=yellow>n/a</>'],
        ['Projects served' => $isRunning ? (implode(', ', $served) ?: '<fg=yellow>none</>') : '<fg=yellow>n/a</>'],
    );

    if ($isRunning) {
        io()->success('Router is running');
    } else {
        io()->warning('Router is not running');
        io()->note('Use "castor docker:router:enable" to start it');
    }
}

#[AsTask(name: 'logs', namespace: 'docker:router', description: 'Show logs from the global Caddy router')]
function router_logs(bool $follow = false): void
{
    if (!is_router_running()) {
        io()->error('Router is not running');
        io()->note('Use "castor docker:router:enable" to start it');
        return;
    }

    $command = ['docker', 'logs', get_router_name()];

    if ($follow) {
        $command[] = '-f';
    } else {
        $command[] = '--tail';
        $command[] = '100';
    }

    run($command, context: context()->withTty());
}

#[AsTask(name: 'restart', namespace: 'docker:router', description: 'Restart the global Caddy router')]
function router_restart(): void
{
    io()->title('Restarting Castor Docker Router');

    if (!is_router_running()) {
        io()->warning('Router is not currently running');
    }

    router_disable();
    router_enable();
}
