<?php

declare(strict_types=1);

namespace Castor\Docker;

use Castor\Attribute\AsTask;
use Castor\Context;
use Composer\InstalledVersions;
use Symfony\Component\Process\ExecutableFinder;

use function Castor\capture;
use function Castor\context;
use function Castor\fs;
use function Castor\get_cache;
use function Castor\io;
use function Castor\run;
use function Castor\yaml_dump;
use function Castor\yaml_parse;

/**
 * Names its compose project, its container and its own network
 * ("<name>_default").
 */
function get_router_name(): string
{
    return 'castor-docker-router';
}

function get_router_directory(): string
{
    return $_SERVER['HOME'] . '/.castor/docker/router';
}

function get_router_compose_file(): string
{
    return get_router_directory() . '/compose.yaml';
}

/**
 * Holds the optional mkcert CA. Never derived from a project path: a relative
 * one would resolve against the project directory when written from PHP, but
 * against the router directory when mounted by compose.
 */
function get_router_certs_directory(): string
{
    return get_router_directory() . '/certs';
}

/**
 * The base Caddyfile is passed as a compose config rather than baked in with a
 * Dockerfile, so enabling the router never depends on a project's vendor
 * directory being present.
 */
function get_router_image(): string
{
    return 'lucaslorentz/caddy-docker-proxy:2.13.1-alpine';
}

/**
 * The socket of the Docker daemon the projects run on, which the router has to
 * watch to see their "caddy.*" labels.
 *
 * Not always /var/run/docker.sock: a rootless daemon, Colima or a CI job put
 * theirs elsewhere, and /var/run/docker.sock may then be a *different* daemon
 * where the project's containers do not exist — the router would come up, see
 * no label and serve nothing. Only a unix DOCKER_HOST can be bind-mounted.
 */
function get_docker_socket_path(): string
{
    $socket = $_SERVER['DOCKER_SOCKET_PATH'] ?? null;

    if (\is_string($socket) && '' !== $socket) {
        return $socket;
    }

    $host = $_SERVER['DOCKER_HOST'] ?? null;

    if (\is_string($host) && str_starts_with($host, 'unix://')) {
        return substr($host, \strlen('unix://'));
    }

    return '/var/run/docker.sock';
}

/**
 * On by default: a project routing a domain cannot be reached without the
 * router, and forgetting to start it only shows up as a "connection refused"
 * much later. The environment variable wins over the context, so a CI job or a
 * single shell can turn it off without touching the project.
 */
function is_router_autostart_enabled(?Context $c = null): bool
{
    $env = $_SERVER['CASTOR_DOCKER_ROUTER_AUTOSTART'] ?? null;

    if (\is_string($env) && '' !== $env) {
        $value = filter_var($env, \FILTER_VALIDATE_BOOL, \FILTER_NULL_ON_FAILURE);

        if (null !== $value) {
            return $value;
        }
    }

    $data = ($c ?? context())->data['router_autostart'] ?? null;

    if (\is_bool($data)) {
        return $data;
    }

    return true;
}

/**
 * Unless the file describes a newer router: every project on the machine writes
 * it with the version of the plugin it has installed, and one lagging behind
 * must not take the router back to its older configuration.
 */
function ensure_router_compose(): void
{
    // The certificate directory is mounted by the router, so it must exist
    // beforehand or Docker would create it as root.
    fs()->mkdir([get_router_directory(), get_router_certs_directory()]);

    $existing = get_router_compose_file_labels();

    if (compare_router_configuration($existing['version'], $existing['checksum']) > 0) {
        io()->comment(\sprintf(
            'Keeping the router configuration of castor-php/docker %s, newer than the %s of this project.',
            $existing['version'],
            get_plugin_version(),
        ));

        return;
    }

    $yamlContent = yaml_dump(get_router_compose(), inline: 10);

    fs()->dumpFile(
        get_router_compose_file(),
        "# This file is automatically generated by Castor Docker Plugin\n"
        . "# Do not edit manually - it will be regenerated on router:enable\n\n"
        . $yamlContent
    );
}

/**
 * @return array<string, mixed>
 */
function get_router_compose(): array
{
    $certsDir = get_router_certs_directory();

    // Read at generation time only: the content is embedded in the compose
    // file below, which therefore stays valid even if this plugin is removed.
    $caddyfile = file_get_contents(__DIR__ . '/Resources/router/Caddyfile');

    return [
        'name' => get_router_name(),
        'volumes' => [
            'router-data' => null,
        ],
        'configs' => [
            'caddyfile' => [
                'content' => $caddyfile,
            ],
        ],
        'services' => [
            'router' => [
                'image' => get_router_image(),
                'container_name' => get_router_name(),
                'restart' => 'unless-stopped',
                'environment' => [
                    'CADDY_DOCKER_CADDYFILE_PATH' => '/etc/caddy/Caddyfile',
                ],
                'configs' => [
                    [
                        'source' => 'caddyfile',
                        'target' => '/etc/caddy/Caddyfile',
                    ],
                ],
                'volumes' => [
                    // caddy-docker-proxy watches the socket to build its
                    // configuration from the "caddy.*" labels of the services.
                    get_docker_socket_path() . ':/var/run/docker.sock',
                    'router-data:/data',
                    "{$certsDir}:/certs:cached",
                ],
                'ports' => [
                    '80:80',
                    '443:443',
                ],
                'labels' => [
                    'castor.managed' => 'true',
                    'castor.router' => 'true',
                    // Which plugin created the router, and from what — several
                    // projects share it, each on its own version. The checksum
                    // is also what makes compose recreate the router when only
                    // the content of its inline config changed.
                    'castor.router.version' => get_plugin_version(),
                    'castor.router.checksum' => get_router_checksum(),
                ],
            ],
        ],
    ];
}

/**
 * A release ("0.7.1"), or a branch ("dev-main") for a checkout.
 */
function get_plugin_version(): string
{
    if (class_exists(InstalledVersions::class) && InstalledVersions::isInstalled('castor-php/docker')) {
        return InstalledVersions::getPrettyVersion('castor-php/docker') ?? 'dev-unknown';
    }

    return 'dev-unknown';
}

/**
 * Negative when $a is older than $b, zero when nothing tells them apart.
 *
 * No version at all is a router created before the plugin labelled it, older
 * than anything. A branch ranks above every release, the way composer ranks the
 * default branch. Two branches cannot be ordered.
 */
function compare_plugin_versions(?string $a, ?string $b): int
{
    $rank = static fn(?string $version): int => match (true) {
        null === $version || '' === $version => 0,
        str_starts_with($version, 'dev-') || str_ends_with($version, '-dev') => 2,
        default => 1,
    };

    if ($rank($a) !== $rank($b) || 1 !== $rank($a)) {
        return $rank($a) <=> $rank($b);
    }

    return version_compare(ltrim((string) $a, 'v'), ltrim((string) $b, 'v'));
}

/**
 * Two versions of the plugin shipping the same Caddyfile and image give the
 * same digest.
 */
function get_router_checksum(): string
{
    $caddyfile = (string) file_get_contents(__DIR__ . '/Resources/router/Caddyfile');

    return substr(hash('xxh128', $caddyfile . "\n" . get_router_image()), 0, 12);
}

/**
 * Zero when a router created by $version from $checksum is the one this plugin
 * would create, negative when it should give way to it, positive when it should
 * be kept.
 *
 * Only a different configuration is worth replacing a router serving every
 * project of the machine, however far apart the plugin versions are. Between
 * two branches this one wins: that is a plugin developer switching branches.
 */
function compare_router_configuration(?string $version, ?string $checksum, ?string $pluginVersion = null, ?string $pluginChecksum = null): int
{
    $pluginVersion ??= get_plugin_version();
    $pluginChecksum ??= get_router_checksum();

    if ($checksum === $pluginChecksum) {
        return 0;
    }

    return compare_plugin_versions($version, $pluginVersion) > 0 ? 1 : -1;
}

/**
 * @return array{version: ?string, checksum: ?string}
 */
function parse_router_labels(mixed $labels): array
{
    $labels = normalize_compose_labels($labels);

    return [
        'version' => ($labels['castor.router.version'] ?? '') ?: null,
        'checksum' => ($labels['castor.router.checksum'] ?? '') ?: null,
    ];
}

/**
 * @return array{version: ?string, checksum: ?string}
 */
function get_router_compose_file_labels(): array
{
    $file = get_router_compose_file();
    $compose = file_exists($file) ? yaml_parse((string) file_get_contents($file)) : null;

    return parse_router_labels($compose['services']['router']['labels'] ?? null);
}

/**
 * @return array{version: ?string, checksum: ?string}
 */
function get_router_container_labels(): array
{
    $labels = json_decode(capture(
        ['docker', 'inspect', '-f', '{{json .Config.Labels}}', get_router_name()],
        context: context()->withQuiet()->withAllowFailure()
    ), true);

    return parse_router_labels($labels);
}

/**
 * A router outlives the projects and serves all of them, each on its own
 * version of the plugin: the one running may have been created by an older
 * version, whose configuration lacks what a task relies on.
 */
function is_router_up_to_date(): bool
{
    $labels = get_router_container_labels();

    return compare_router_configuration($labels['version'], $labels['checksum']) >= 0;
}

/**
 * Starting the router recreates an older configuration, but one that already
 * runs is left alone: it serves every project of the machine, and when to
 * interrupt them is the user's call.
 */
function warn_if_router_outdated(?string $consequence = null): void
{
    if (is_router_up_to_date()) {
        return;
    }

    io()->warning(array_filter([
        \sprintf(
            'The global router was created by castor-php/docker %s, and runs an older configuration than the %s of this project.',
            get_router_container_labels()['version'] ?? '(version unknown)',
            get_plugin_version(),
        ),
        $consequence,
        'Run "castor docker:router:restart" to apply the new one. It briefly interrupts every project it serves.',
    ]));
}

function is_router_running(): bool
{
    try {
        $output = capture(
            ['docker', 'ps', '--filter', 'name=' . get_router_name(), '--filter', 'status=running', '--format', '{{.Names}}'],
            context: context()->withQuiet()->withAllowFailure()
        );

        return trim($output) === get_router_name();
    } catch (\Throwable) {
        return false;
    }
}

/**
 * Null when the router is not running.
 *
 * @return array{version: ?string, checksum: ?string, socket: ?string, networks: list<string>}|null
 */
function get_running_router(): ?array
{
    if (!is_router_running()) {
        return null;
    }

    $socket = trim(capture(
        ['docker', 'inspect', '--format', '{{range .Mounts}}{{if eq .Destination "/var/run/docker.sock"}}{{.Source}}{{end}}{{end}}', get_router_name()],
        context: context()->withQuiet()->withAllowFailure(),
        onFailure: '',
    ));

    return [
        ...get_router_container_labels(),
        'socket' => '' === $socket ? null : $socket,
        'networks' => get_router_networks(),
    ];
}

/**
 * The projects with a running container carrying a "caddy" label. A routed
 * container compose did not create names no project, so its own name stands
 * for it.
 *
 * @return list<string>
 */
function get_routed_projects(): array
{
    try {
        $found = capture(
            ['docker', 'ps', '--filter', 'label=caddy', '--format', '{{.Label "com.docker.compose.project"}}|{{.Names}}'],
            context: context()->withQuiet()->withAllowFailure()
        );
    } catch (\Throwable) {
        return [];
    }

    $projects = [];

    foreach (explode("\n", trim($found)) as $line) {
        if ('' === trim($line)) {
            continue;
        }

        [$project, $name] = array_pad(explode('|', trim($line), 2), 2, '');
        $projects[trim($project) ?: trim($name)] = true;
    }

    unset($projects['']);
    ksort($projects);

    return array_keys($projects);
}

/**
 * What both "docker:router:enable" and the autostart do.
 *
 * @return list<string> the networks of the already-running projects it joined
 */
function start_router(): array
{
    ensure_router_compose();

    $socket = get_docker_socket_path();

    // A router watching a socket that is not there answers nothing on 443,
    // with only "connection refused" on the caller's side to go by.
    if (!file_exists($socket)) {
        io()->warning([
            \sprintf('The Docker socket %s does not exist.', $socket),
            'The router builds its routes from the labels it reads there, so it will serve nothing at all.',
            'Set DOCKER_SOCKET_PATH to the socket of the daemon your projects run on.',
        ]);
    }

    install_certificate_authority();

    run(['docker', 'compose', '-f', get_router_compose_file(), 'up', '-d']);

    // "docker:up" only attaches the router to its project network when the
    // router is already up at that time.
    $networks = connect_router_to_running_projects();

    $routerCache = get_cache()->getItem('infrastructure.router.enabled');
    $routerCache->set(true);
    get_cache()->save($routerCache);

    return $networks;
}

/**
 * False when there is no compose file to stop it with, which means the router
 * was never set up here.
 */
function stop_router(): bool
{
    $composeFile = get_router_compose_file();

    if (!file_exists($composeFile)) {
        return false;
    }

    // The tunnels are on the router network, which compose cannot remove while
    // anything is still attached to it.
    close_all_tunnels();

    run(['docker', 'compose', '-f', $composeFile, 'down']);

    $routerCache = get_cache()->getItem('infrastructure.router.enabled');
    $routerCache->set(false);
    get_cache()->save($routerCache);

    return true;
}

/**
 * Called before compose starts the containers, because the project network is
 * joined right after and a router that is not up yet cannot join it.
 *
 * A project routing no domain never triggers this: it has nothing for the
 * router to serve.
 */
function autostart_router(?Context $c = null): void
{
    $c ??= context();

    if (!get_project_urls($c)) {
        return;
    }

    // Whoever started it, this router serves the project: being outdated
    // matters with the autostart off too.
    if (is_router_running()) {
        warn_if_router_outdated();

        return;
    }

    if (!is_router_autostart_enabled($c)) {
        return;
    }

    io()->comment('Starting the global Caddy router, which this project needs to serve its domains.');

    try {
        start_router();
    } catch (\Throwable $e) {
        // The project itself can still come up: only its domains will not
        // answer.
        io()->warning('Could not start the global router: ' . $e->getMessage());
        io()->note('Start it yourself with "castor docker:router:enable".');
    }
}

/**
 * Stop the router once no project is left for it to serve, however it was
 * started: it would be holding ports 80 and 443 for no one, and the next
 * project that needs it starts it again. Turn the autostart off to keep one
 * running for good.
 */
function autostop_router(?Context $c = null): void
{
    $c ??= context();

    if (!is_router_autostart_enabled($c) || !get_project_urls($c) || !is_router_running()) {
        return;
    }

    $projects = get_routed_projects();

    if ($projects) {
        io()->comment(\sprintf('Leaving the global Caddy router up, it still serves: %s.', implode(', ', $projects)));

        return;
    }

    io()->comment('Stopping the global Caddy router, no project needs it anymore.');

    try {
        stop_router();
    } catch (\Throwable $e) {
        io()->warning('Could not stop the global router: ' . $e->getMessage());
    }
}

function install_certificate_authority(): void
{
    $certsDir = get_router_certs_directory();
    $caddyDir = $certsDir . '/caddy';

    $mkcert = (new ExecutableFinder())->find('mkcert');

    if (!$mkcert) {
        io()->comment('mkcert is not installed: the router will use its own local CA (browsers will show a security warning). Install mkcert (https://github.com/FiloSottile/mkcert) for locally-trusted certificates.');

        return;
    }

    $caRoot = trim(capture(['mkcert', '-CAROOT']));

    if (!is_dir($caRoot) || !file_exists("{$caRoot}/rootCA.pem") || !file_exists("{$caRoot}/rootCA-key.pem")) {
        io()->warning('You must have the mkcert CA installed on your host with the "mkcert -install" command.');

        return;
    }

    fs()->mkdir($caddyDir);

    if (fs()->exists("{$certsDir}/rootCA.pem")) {
        fs()->remove("{$certsDir}/rootCA.pem");
    }

    if (fs()->exists("{$certsDir}/rootCA-key.pem")) {
        fs()->remove("{$certsDir}/rootCA-key.pem");
    }

    fs()->copy("{$caRoot}/rootCA.pem", "{$certsDir}/rootCA.pem", true);
    fs()->copy("{$caRoot}/rootCA-key.pem", "{$certsDir}/rootCA-key.pem", true);

    // The mkcert root is created with "pathlen:0", so it may only sign leaves,
    // not the intermediate Caddy signs with by default: pointing both at the
    // mkcert root keeps the chain valid ("path length constraint exceeded"
    // otherwise).
    fs()->dumpFile("{$caddyDir}/ca.caddy", <<<'CADDY'
        pki {
            ca local {
                root {
                    cert /certs/rootCA.pem
                    key /certs/rootCA-key.pem
                }
                intermediate {
                    cert /certs/rootCA.pem
                    key /certs/rootCA-key.pem
                }
            }
        }
        CADDY);

    io()->comment('Using the mkcert CA for locally-trusted certificates.');
}

/**
 * Projects deliberately do not share a network: the router is the only
 * container with a foot in several of them, so two projects exposing a service
 * under the same name never collide in the Docker DNS. caddy-docker-proxy
 * resolves "{{upstreams}}" to container IPs, so it only needs to be routable.
 *
 * The project domains are passed as network aliases, so they also resolve to
 * the router through the Docker DNS — a fallback for when the extra_hosts of
 * add_project_extra_hosts() are turned off. Docker keeps the aliases of a
 * network it is already a member of, so they only apply when it really joins.
 *
 * @param list<string> $aliases
 */
function connect_router_to_network(string $network, array $aliases = []): void
{
    if (!is_router_running()) {
        return;
    }

    $command = ['docker', 'network', 'connect'];

    foreach ($aliases as $alias) {
        $command[] = '--alias';
        $command[] = $alias;
    }

    $command[] = $network;
    $command[] = get_router_name();

    run($command, context: context()->withQuiet()->withAllowFailure());
}

/**
 * Required before "docker compose down": Docker refuses to remove a network
 * that still has an endpoint, leaving a dangling network and an error behind.
 */
function disconnect_router_from_network(string $network): void
{
    if (!is_router_running()) {
        return;
    }

    run(
        ['docker', 'network', 'disconnect', $network, get_router_name()],
        context: context()->withQuiet()->withAllowFailure()
    );
}

/**
 * @return list<string>
 */
function get_router_networks(): array
{
    $found = trim(capture(
        ['docker', 'inspect', '-f', '{{range $k, $v := .NetworkSettings.Networks}}{{$k}}{{"\n"}}{{end}}', get_router_name()],
        context: context()->withQuiet()->withAllowFailure()
    ));

    return array_values(array_filter(array_map(trim(...), explode("\n", $found))));
}

/**
 * Enabling the router after the projects are up would otherwise route nothing
 * until the next "docker:up".
 *
 * @return list<string>
 */
function connect_router_to_running_projects(): array
{
    $ids = array_filter(explode("\n", trim(capture(
        ['docker', 'ps', '--filter', 'label=caddy', '--format', '{{.ID}}'],
        context: context()->withQuiet()->withAllowFailure()
    ))));

    $networks = [];

    foreach ($ids as $id) {
        $found = trim(capture(
            ['docker', 'inspect', '-f', '{{range $k, $v := .NetworkSettings.Networks}}{{$k}}{{"\n"}}{{end}}', $id],
            context: context()->withQuiet()->withAllowFailure()
        ));

        foreach (array_filter(explode("\n", $found)) as $network) {
            $networks[trim($network)] = true;
        }
    }

    unset($networks[get_router_name() . '_default']);

    foreach (array_keys($networks) as $network) {
        connect_router_to_network($network);
    }

    return array_keys($networks);
}

#[AsTask(name: 'enable', namespace: 'docker:router', description: 'Enable and start the global Caddy router')]
function router_enable(): void
{
    io()->title('Enabling Castor Docker Router');

    $networks = start_router();

    io()->comment('Router compose file created at: ' . get_router_compose_file());

    foreach ($networks as $network) {
        io()->comment(\sprintf('Joined the network of a running project: %s', $network));
    }

    io()->success('Router enabled and running!');
    io()->note([
        'The router is now running globally at http://localhost:80 and https://localhost:443',
        'All projects using castor-docker will automatically connect to this router',
        'Use "castor docker:router:disable" to stop the router',
    ]);
}

#[AsTask(name: 'disable', namespace: 'docker:router', description: 'Stop and disable the global Caddy router')]
function router_disable(): void
{
    io()->title('Disabling Castor Docker Router');

    if (!stop_router()) {
        io()->warning('Router compose file not found. Router may not be set up.');

        return;
    }

    io()->success('Router disabled');
    io()->note('Use "castor docker:router:enable" to start it again');

    if (is_router_autostart_enabled()) {
        io()->note('The next "castor docker:up" of a project routing a domain will start it again. Set "router_autostart" to false, or CASTOR_DOCKER_ROUTER_AUTOSTART=0, to keep it down.');
    }
}

/**
 * How the running router compares to the one of this project.
 */
function describe_router_configuration(): string
{
    $labels = get_router_container_labels();
    $version = $labels['version'] ?? '(version unknown)';

    return match (compare_router_configuration($labels['version'], $labels['checksum']) <=> 0) {
        0 => \sprintf('<fg=green>Up to date, from castor-php/docker %s</>', $version),
        1 => \sprintf('<fg=green>From castor-php/docker %s, newer than the %s of this project</>', $version, get_plugin_version()),
        -1 => \sprintf('<fg=yellow>From castor-php/docker %s, older than the %s of this project: run "castor docker:router:restart"</>', $version, get_plugin_version()),
    };
}

#[AsTask(name: 'status', namespace: 'docker:router', description: 'Show the status of the global Caddy router')]
function router_status(): void
{
    $isRunning = is_router_running();
    $cacheItem = get_cache()->getItem('infrastructure.router.enabled');
    $isEnabled = $cacheItem->isHit() && $cacheItem->get() === true;
    $served = $isRunning ? get_routed_projects() : [];

    io()->title('Castor Docker Router Status');

    io()->definitionList(
        ['Status' => $isRunning ? '<fg=green>Running</>' : '<fg=red>Stopped</>'],
        ['Enabled in cache' => $isEnabled ? '<fg=green>Yes</>' : '<fg=yellow>No</>'],
        ['Autostart' => is_router_autostart_enabled() ? '<fg=green>On</>' : '<fg=yellow>Off</>'],
        ['Compose file' => file_exists(get_router_compose_file()) ? get_router_compose_file() : '<fg=red>Not found</>'],
        ['Container name' => get_router_name()],
        ['Ports' => '80:80, 443:443'],
        ['Configuration' => $isRunning ? describe_router_configuration() : '<fg=yellow>n/a</>'],
        ['Joined networks' => $isRunning ? implode(', ', get_router_networks()) : '<fg=yellow>n/a</>'],
        ['Projects served' => $isRunning ? (implode(', ', $served) ?: '<fg=yellow>none</>') : '<fg=yellow>n/a</>'],
    );

    if ($isRunning) {
        io()->success('Router is running');
    } else {
        io()->warning('Router is not running');
        io()->note('Use "castor docker:router:enable" to start it');
    }
}

#[AsTask(name: 'logs', namespace: 'docker:router', description: 'Show logs from the global Caddy router')]
function router_logs(bool $follow = false): void
{
    if (!is_router_running()) {
        io()->error('Router is not running');
        io()->note('Use "castor docker:router:enable" to start it');
        return;
    }

    $command = ['docker', 'logs', get_router_name()];

    if ($follow) {
        $command[] = '-f';
    } else {
        $command[] = '--tail';
        $command[] = '100';
    }

    run($command, context: context()->withTty());
}

#[AsTask(name: 'restart', namespace: 'docker:router', description: 'Restart the global Caddy router')]
function router_restart(): void
{
    io()->title('Restarting Castor Docker Router');

    if (!is_router_running()) {
        io()->warning('Router is not currently running');
    }

    router_disable();
    router_enable();
}
