name: CI

on:
  push:
    branches: [ main ]
  pull_request: ~

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer, castor

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Unit and transform tests
        run: vendor/bin/phpunit --testsuite unit,transform

      - name: Integration tests
        run: vendor/bin/phpunit --testsuite integration

  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer, castor

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: PHPStan
        run: castor qa:phpstan

  cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Castor
        uses: castor-php/setup-castor@v1.0.0

      - name: PHP CS Fixer
        run: castor qa:cs --dry-run
