name: Build and push Twig Docker Builder Image

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - 'twig-dockerfile/**'
      - 'tests/E2e/**'

permissions:
  contents: read
  packages: write

jobs:
  build_test_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Build the image
        run: docker build twig-dockerfile --tag ghcr.io/castor-php/twig-dockerfile:latest

      - name: End-to-end test
        run: vendor/bin/phpunit --testsuite e2e
        env:
          RUN_E2E: '1'
          E2E_IMAGE: ghcr.io/castor-php/twig-dockerfile:latest

      - name: Push the image
        if: github.event_name == 'push'
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
          docker push ghcr.io/castor-php/twig-dockerfile:latest
